Pass dirs argument to xml_suey
Traceback (most recent call last):
  File "/MultiC/multic/cli/MultiCompartmentSegment/MultiCompartmentSegment.py", line 71, in <module>
    main(CLIArgumentParser().parse_args())
  File "/MultiC/multic/cli/MultiCompartmentSegment/MultiCompartmentSegment.py", line 68, in main
    run_it(args)
  File "../segmentationschool/segmentation_school.py", line 45, in run_it
    main(args)
  File "../segmentationschool/segmentation_school.py", line 37, in main
    predict(args=args)
  File "../segmentationschool/Codes/IterativePredict_1X.py", line 210, in predict
    xml_suey(wsiMask=wsiMask, args=args, classNum=classNum, downsample=downsample,glob_offset=[0,0])
TypeError: xml_suey() missing 1 required positional argument: 'dirs'
DockerException: Non-zero exit code from docker container (1).